
export { default as Blog } from './blog/Blog'
export { default as Home } from './home/Home'
export { default as Login } from './login/Login'
export { default as Profile } from './profiles/Profile'
export { default as Projects } from './projects/Projects'
export { default as Register } from './register/Register'
export { default as Single } from  './singlePost/Single'
export { default as Tutoring } from './tutoring/Tutoring'
export { default as Write } from './write/Write'
export { default as About } from './about/About'